import '././commands/extrato'
import '././commands/home'
import '././commands/login'
import '././commands/pagamentos'
import '././commands/register'
import '././commands/saque'
import '././commands/transfer'